### ISSUE TITLE
Solution not building

### ISSUE THREAD

**Issue by payini** [cshtml5/CSHTML5.Samples.Showcase#3]
I cloned the master branch and it's not building for me. It seems to be an issue with getting the NuGet package properly.

I removed and re-added the 1.0.0-alpha-005 package and solved one issue but still wouldn't build.

ElementToDrag is not being recognized because of the package problem.

See picture below:

![image](https://user-images.githubusercontent.com/2638642/87638732-20f05880-c6f9-11ea-86b3-d32d1459de3a.png)

**Comment by cshtml5** [comment]
Just fixed. Thanks a lot for reporting this issue.

**Comment by payini** [comment]
Yep, it worked like a charm this time. Thank you.
